### ISSUE TITLE
Change name of project

### ISSUE THREAD

**Issue by bnvk** [bnvk/Conjuror#30]
While I like the name `Beardo` and it has given me a few chuckles, I think I would like to finally package this for npm as I dip into the next round of things I plan to do for the project. Reasons for changing name are: 

- I like the whole "magic" metaphor more than my initial joke about beards
- It is heavily gendered, which is, um, ok, but not ideal
- The name Beardo is already taken in NPM

So here is some magic themed names that I like (and are available in NPM)

- conjuror
- enchantment
- sorceress
- witchery

Interestingly, there's some HTTP server or something called [Warlock](https://www.npmjs.com/search?q=warlock) that used similar naming ideas "spells" and such.

@simonv3 since you're the only other contributor / user AFAIK, what do you think? Personally, i'm leaning towards `Conjuror` because it's non-gendered and evokes a certain "magical" feeling that I was hoping for!

**Comment by simonv3** [comment]
@bnvk Sounds good to me! I like conjuror.

(I agree with all that you say above, just don't really have anything to contribute outside of that :P)

**Comment by bnvk** [comment]
done in d75e4a504f3c091e2b1fe8a06678c13b322675c5
