### ISSUE TITLE
No output on first try

### ISSUE THREAD

**Issue by gniezen** [bnvk/Conjuror#34]
I've ran Conjuror for the first time using

    node conjuror.js -i data/_template.json -t beardo

but I don't see any output. I've installed `node` and run `sudo npm install` to make sure all dependencies are installed. Below output of `mocha test` and directory structure.

![screenshot from 2015-05-15 16 22 29](https://cloud.githubusercontent.com/assets/418233/7656083/1e911fde-fb20-11e4-9241-7cedd5df6260.png)
![screenshot from 2015-05-15 16 27 31](https://cloud.githubusercontent.com/assets/418233/7656085/220bd00a-fb20-11e4-9afb-1215455b9afb.png)

**Comment by bnvk** [comment]
@gniezen oh man, I don't know how I missed this issue ages ago... I don't think I ever saw it. Thanks for checking my lil project out. It should be working, these days... myself and Simon use it all the time for our invocing! 

Anywho, more work will happen soonish :package: :smile:
